export enum MediaOwnerTypeEnum {
  PRESTADOR = 'PRESTADOR',
  SEDE = 'SEDE',
  SERVICIO_HABILITADO = 'SERVICIO_HABILITADO',
  VISITA = 'VISITA',
  ACTA_VISITA = 'ACTA_VISITA',
  AUTOEVALUACION = 'AUTOEVALUACION',
  NOVEDAD = 'NOVEDAD',
  CERTIFICADO = 'CERTIFICADO',
  DISTINTIVO = 'DISTINTIVO',
  CRITERIO = 'CRITERIO',
  USUARIO = 'USUARIO',
  OTRO = 'OTRO',
}
