export enum NovedadTipoEnum {
  CAMBIO_CAPACIDAD = 'CAMBIO_CAPACIDAD',
  CAMBIO_SERVICIO = 'CAMBIO_SERVICIO',
  CAMBIO_SEDE = 'CAMBIO_SEDE',
  CAMBIO_PRESTADOR = 'CAMBIO_PRESTADOR',
  CIERRE = 'CIERRE',
  OTRO = 'OTRO',
}
